<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE list [
  <!ELEMENT list (word+)>
  <!ELEMENT word    (english+, image+, spanish*, meaning*)>
  <!ELEMENT english (#PCDATA)>
  <!ELEMENT image   (#PCDATA)>
  <!ELEMENT spanish (#PCDATA)>
  <!ELEMENT meaning (#PCDATA)>
]>
 <list>
	 <word>
	   <english>Apple</english>
	   <image>apple</image>
	   <spanish>Manzana</spanish>
	   <meaning>Fruit that grows on a tree</meaning>
	 </word>
 	 <word>
	   <english>Mouse</english>
	   <image>mouse</image>
	   <spanish>Raton</spanish>
	   <meaning>Small rodent</meaning>
	 </word>
 	 <word>
	   <english>Garlic</english>
	   <image>garlic</image>
	 </word>
</list>